import datetime as d
someday = d.datetime.now()#.strftime("%Y-%m-%d %H:%M:%S")
print(someday)
print(someday.min)
print(someday.max)
print(someday.year)
print(someday.month)
print(someday.day)
print(someday.hour)
print(someday.minute)
